#!/bin/bash
# scripts/upgrade

app=$1
cd "/var/www/$app" || exit 1

git pull origin main
source venv/bin/activate
pip install -r requirements.txt

systemctl reload nginx
systemctl restart uwsgi-app@$app

echo "✅ Mise à jour terminée"