#!/bin/bash

ynh_script_progression --message="Mise à jour de l'application"
# Ici tu pourrais faire un git pull ou recopier la nouvelle version
cp -r velocio-POI/* /var/www/velocio-poi
ynh_script_progression --message="Mise à jour terminée"